### PR TITLE
MacOS build instruction fixes

### LINKED ISSUE #60: V1.91 Compiles on Mac But with Errors
So I managed to compile V1.91 on a Mac, but I get some very weird results...
FYI: I used cmake for this

1. The outputted file in not a .APP like the v1.5 version (but I think you say that in the instructions).
2. libpng warning: iCCP: known incorrect sRGB profile
3. You have to MOGRIFY the PNGs in the resources folder, or...
4. ...you get libpng errors when running the Unix executable that is output by the make process
5. The outputted file is a fifth of the size of its predecessor (3.9mb).
6. Warnings are produced that OPERATOR and CREATED are deprecated
7. For qmake, `make lcopy` doesn't work `make: *** No rule to make target 'lcopy'.  Stop.`
8. You seem to have to `qmake` in the `SRC` folder then `make lcopy` works, but i still have to run `make` to get an output
9. During the qmake process `datautils.c:26:10: fatal error: 'libxml/xmlmemory.h' file not found`
10. During the qmake process `clang: error: linker command failed with exit code 1 (use -v to see invocation)`

### PR DESCRIPTION
**Pull request by nighto**
Fixes #60.

### CODE REVIEW

**Comment by prestoncrawford** [comment]
Is this all you had to do? On `make` I'm seeing the following error. 

Consolidate compiler generated dependencies of target vitapkg
[ 31%] Building C object deps/psvlib/pkg/CMakeFiles/vitapkg.dir/pkg_sys.c.o
/Users/prestonc/Downloads/VITA/finalhe-1.92/deps/psvlib/pkg/pkg_sys.c:211:13: error: implicit declaration of function
      '_error_func' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            _error_func(NULL, "ERROR: cannot create '%s' folder\n", path);

**Comment by suicvne** [comment]
I was able to fix the build error on macOS Big Sir (11.3). The result is a 4mb Unix binary called "FinalHE" that I can just double click to open:
by default 2021-06-01 at 3 47 40 PM

I have yet to test it. The cosmic red 1000 I just bought needs to charge before I can try this, but I wanted to ensure I was prepared for when it was charged.


I fixed it by modifying the following files:

deps/psvlib/pkg/pkg_sys.c @ line 176 (after all other includes)
``` c
#ifdef __APPLE__
extern pkg_output_func _output_func;
extern pkg_error_func _error_func;
#endif
```

deps/psvlib/img/backup.c @ line 28 (after all other includes, before defines and pragmas)
``` c
#ifdef __APPLE__
#include <string.h>
#endif
```



I then had a cmake policy 0100 error on version 3.20.0 installed from homebrew, so I then added the following to `src/CMakeLists.txt` (after policy CMP0071 is checked and set to new)
```
if(POLICY CMP0100)
	cmake_policy(SET CMP0100 NEW)
endif ()
```

These are external dependencies, but they're stored in this project's directory. Should I make a pull request here?

**Comment by b4mboo** [comment]
@nighto This was really helpful to me. Thank you! ✨

**Comment by JoeMatt** [comment]
Thank you. 

Confirming this works on macOS Monterey 12.0 Beta with XCode 12.5.1.

```sh
brew install dyld-headers libusb pkg-config qt5
cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/qt@5 .
open src/FinalHE 
```

**Comment by sudot0ph** [comment]
Brew instructions should be `brew install libusb pkg-config qt@5`

followed by `brew link qt@5`, or qmake might not be recognized.

Builds without issues on Big Sur.
